Document: python-dependency-injector
Title: Debian python-dependency-injector Manual
Author: <insert document author here>
Abstract: This manual describes what python-dependency-injector is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-dependency-injector/python-dependency-injector.sgml.gz

Format: postscript
Files: /usr/share/doc/python-dependency-injector/python-dependency-injector.ps.gz

Format: text
Files: /usr/share/doc/python-dependency-injector/python-dependency-injector.text.gz

Format: HTML
Index: /usr/share/doc/python-dependency-injector/html/index.html
Files: /usr/share/doc/python-dependency-injector/html/*.html
